<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Google.Protobuf" Version="3.34.1" />
      <PackageReference Include="Grpc.Core.Api" Version="2.76.0" />
      <PackageReference Include="Grpc.Tools" Version="2.80.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>
    
    <ItemGroup>
        <Protobuf Include="Protos\ImageProcessor\image_processor.proto" ProtoRoot="Protos" GrpcServices="Both" Access="Public" />
        <Protobuf Include="Protos\ImageProcessor\common.proto" ProtoRoot="Protos" GrpcServices="None" Access="Public" />
        <Protobuf Include="Protos\ImageProcessor\filters\filter.proto" ProtoRoot="Protos" GrpcServices="None" Access="Public" />
        <Protobuf Include="Protos\ImageProcessor\filters\grayscale_filter.proto" ProtoRoot="Protos" GrpcServices="None" Access="Public" />
        <Protobuf Include="Protos\ImageProcessor\filters\gamma_filter.proto" ProtoRoot="Protos" GrpcServices="None" Access="Public" />
        <Protobuf Include="Protos\ImageProcessor\filters\sharpen_filter.proto" ProtoRoot="Protos" GrpcServices="None" Access="Public" />
        <Protobuf Include="Protos\ImageProcessor\filters\edge_detect_filter.proto" ProtoRoot="Protos" GrpcServices="None" Access="Public" />
        <Protobuf Include="Protos\ImageProcessor\filters\time_warp_filter.proto" ProtoRoot="Protos" GrpcServices="None" Access="Public" />
    </ItemGroup>

</Project>
