syntax = "proto3";

option csharp_namespace = "MMS.Contracts";

package image_processor;

import "ImageProcessor/filters/grayscale_filter.proto";
import "ImageProcessor/filters/gamma_filter.proto";
import "ImageProcessor/filters/sharpen_filter.proto";
import "ImageProcessor/filters/edge_detect_filter.proto";
import "ImageProcessor/filters/time_warp_filter.proto";
import "ImageProcessor/filters/pixelate_filter.proto";
import "ImageProcessor/filters/bill_atkinson_filter.proto";

message ImageFilter {
  oneof Filter {
    GrayscaleFilter Grayscale = 1;
    GammaFilter Gamma = 2;
    SharpenFilter Sharpen = 3;
    EdgeDetectFilter EdgeDetect = 4;
    TimeWarpFilter TimeWarp = 6;
    PixelateFilter Pixelate = 7;
    BillAtkinsonFilter BillAtkinson = 8;
  }
}
