<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\MMS.Contracts\MMS.Contracts.csproj" />
      <ProjectReference Include="..\MMS.Core\MMS.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="DotNetEnv" Version="3.2.0" />
      <PackageReference Include="Grpc.Net.Client" Version="2.64.0" />
      <PackageReference Include="Syncfusion.PropertyGrid.WPF" Version="33.2.10" />
    </ItemGroup>

</Project>
