syntax = "proto3";

option csharp_namespace = "MMS.Contracts";

package image_processor;

import "ImageProcessor/common.proto";
import "ImageProcessor/filters/filter.proto";

service ImageProcessor {
  rpc ProcessImage(stream ProcessImageRequest) returns (stream ProcessImageResponse);
}

message ProcessImageRequest {
  oneof payload {
    ImageHeader Header = 1;
    ImageChunk Chunk = 2;
  }
}

message ImageHeader {
  int32 Width = 1;
  int32 Height = 2;
  repeated ImageFilter Filters = 4;
}

message ProcessImageResponse {  
  oneof payload {
    ProcessImageResult Result = 1;
    ImageChunk Chunk = 2;
  }
}
